### Cleaning Data to 2018

In [1]:
import pandas as pd

df1 = pd.read_csv('../data/rawData/touringplans_2018.csv', quotechar='"', skiprows=[14312, 33475])
display(df1.head())

,park_date,wait_hour,attraction_name,wait_minutes_actual_avg,wait_minutes_posted_avg,attraction_wait_per_hundred_average,attraction_duration,attraction_park,attraction_land,park_open,park_close,park_extra_magic_morning,park_extra_magic_evening,park_ticket_season,park_temperature_average,park_temperature_high,attraction_short_name
0,2018-06-30,7,Alien Swirling Saucers,NaN,150.000000,10.0,2.5,Disney's Hollywood Studios,Toy Story Land,08:00:00,23:00:00,0,0,peak,79.44,85.29,Alien Saucers
1,2018-06-30,8,Alien Swirling Saucers,NaN,127.083333,10.0,2.5,Disney's Hollywood Studios,Toy Story Land,08:00:00,23:00:00,0,0,peak,79.44,85.29,Alien Saucers
2,2018-06-30,9,Alien Swirling Saucers,NaN,91.111111,10.0,2.5,Disney's Hollywood Studios,Toy Story Land,08:00:00,23:00:00,0,0,peak,79.44,85.29,Alien Saucers
3,2018-06-30,10,Alien Swirling Saucers,NaN,136.000000,10.0,2.5,Disney's Hollywood Studios,Toy Story Land,08:00:00,23:00:00,0,0,peak,79.44,85.29,Alien Saucers
4,2018-06-30,11,Alien Swirling Saucers,NaN,173.333333,10.0,2.5,Disney's Hollywood Studios,Toy Story Land,08:00:00,23:00:00,0,0,peak,79.44,85.29,Alien Saucers

In [2]:
print("Unique values in 'park_open' column:")
display(df1['park_open'].unique())

print("\nUnique values in 'park_close' column:")
display(df1['park_close'].unique())

print("\nUnique values in 'attraction_park' column:")
display(df1['attraction_park'].unique())

Unique values in 'park_open' column:

array(['08:00:00', '09:00:00', '07:00:00'], dtype=object)

Unique values in 'park_close' column:

array(['23:00:00', '22:30:00', '22:00:00', '21:00:00', '20:30:00',
       '20:00:00', '24:00:00', '21:30:00', '19:00:00', '18:00:00',
       '25:00:00', '16:30:00'], dtype=object)

Unique values in 'attraction_park' column:

array(["Disney's Hollywood Studios", "Disney's Animal Kingdom",
       'Magic Kingdom', 'Epcot'], dtype=object)

In [3]:
animal_kingdom_df1 = df1[(df1['attraction_park'] == "Disney's Animal Kingdom") & (df1['park_open'] != '7:00:00')]
display(animal_kingdom_df1.head())

,park_date,wait_hour,attraction_name,wait_minutes_actual_avg,wait_minutes_posted_avg,attraction_wait_per_hundred_average,attraction_duration,attraction_park,attraction_land,park_open,park_close,park_extra_magic_morning,park_extra_magic_evening,park_ticket_season,park_temperature_average,park_temperature_high,attraction_short_name
2718,2018-01-01,8,DINOSAUR,NaN,15.000000,3.0,3.5,Disney's Animal Kingdom,DinoLand U.S.A.,08:00:00,20:00:00,0,0,peak,50.56,58.63,DINOSAUR
2719,2018-01-01,9,DINOSAUR,NaN,18.333333,3.0,3.5,Disney's Animal Kingdom,DinoLand U.S.A.,08:00:00,20:00:00,0,0,peak,50.56,58.63,DINOSAUR
2720,2018-01-01,10,DINOSAUR,NaN,23.750000,3.0,3.5,Disney's Animal Kingdom,DinoLand U.S.A.,08:00:00,20:00:00,0,0,peak,50.56,58.63,DINOSAUR
2721,2018-01-01,11,DINOSAUR,NaN,24.000000,3.0,3.5,Disney's Animal Kingdom,DinoLand U.S.A.,08:00:00,20:00:00,0,0,peak,50.56,58.63,DINOSAUR
2722,2018-01-01,12,DINOSAUR,NaN,31.875000,3.0,3.5,Disney's Animal Kingdom,DinoLand U.S.A.,08:00:00,20:00:00,0,0,peak,50.56,58.63,DINOSAUR

In [4]:
print("Unique values in 'park_open' column:")
display(animal_kingdom_df1['park_open'].unique())

print("\nUnique values in 'park_close' column:")
display(animal_kingdom_df1['park_close'].unique())

print("\nUnique values in 'attraction_park' column:")
display(animal_kingdom_df1['attraction_park'].unique())

Unique values in 'park_open' column:

array(['08:00:00', '09:00:00'], dtype=object)

Unique values in 'park_close' column:

array(['20:00:00', '21:00:00', '20:30:00', '22:00:00', '21:30:00',
       '23:00:00', '22:30:00', '19:00:00'], dtype=object)

Unique values in 'attraction_park' column:

array(["Disney's Animal Kingdom"], dtype=object)

In [5]:
df2 = pd.read_csv('../data/rawData/parks_metadata_raw.csv', quotechar='"')
display(df2.head())

,date,wdw_ticket_season,dayofweek,dayofyear,weekofyear,monthofyear,year,season,holidaypx,holidaym,...,hsfirewks,akprdday,akprddt1,akprddt2,akprddn,akfiren,akshwngt,akshwnt1,akshwnt2,akshwnn
0,2015-01-01,NaN,5,0,0,1,2015,CHRISTMAS PEAK,0,5,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1,2015-01-02,NaN,6,1,0,1,2015,CHRISTMAS,2,5,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
2,2015-01-03,NaN,7,2,0,1,2015,CHRISTMAS,3,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
3,2015-01-04,NaN,1,3,1,1,2015,CHRISTMAS,4,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
4,2015-01-05,NaN,2,4,1,1,2015,CHRISTMAS,5,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN

In [6]:
df2 = df2.drop(['holidayn', 'holidaym', 'holidaypx'], axis=1)
display(df2.head())

,date,wdw_ticket_season,dayofweek,dayofyear,weekofyear,monthofyear,year,season,holiday,wdwticketseason,...,hsfirewks,akprdday,akprddt1,akprddt2,akprddn,akfiren,akshwngt,akshwnt1,akshwnt2,akshwnn
0,2015-01-01,NaN,5,0,0,1,2015,CHRISTMAS PEAK,1,NaN,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1,2015-01-02,NaN,6,1,0,1,2015,CHRISTMAS,0,NaN,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
2,2015-01-03,NaN,7,2,0,1,2015,CHRISTMAS,0,NaN,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
3,2015-01-04,NaN,1,3,1,1,2015,CHRISTMAS,0,NaN,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
4,2015-01-05,NaN,2,4,1,1,2015,CHRISTMAS,0,NaN,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN

In [7]:
df2_2018 = df2[df2['year'] == 2018]
display(df2_2018.head())

,date,wdw_ticket_season,dayofweek,dayofyear,weekofyear,monthofyear,year,season,holiday,wdwticketseason,...,hsfirewks,akprdday,akprddt1,akprddt2,akprddn,akfiren,akshwngt,akshwnt1,akshwnt2,akshwnn
1096,2018-01-01,peak,2,0,0,1,2018,CHRISTMAS PEAK,1,peak,...,1,0,NaN,NaN,NaN,NaN,2,66600.0,71100.0,Rivers of Light
1097,2018-01-02,peak,3,1,0,1,2018,CHRISTMAS,0,peak,...,1,0,NaN,NaN,NaN,NaN,2,66600.0,71100.0,Rivers of Light
1098,2018-01-03,peak,4,2,0,1,2018,CHRISTMAS,0,peak,...,1,0,NaN,NaN,NaN,NaN,2,66600.0,71100.0,Rivers of Light
1099,2018-01-04,regular,5,3,0,1,2018,CHRISTMAS,0,regular,...,1,0,NaN,NaN,NaN,NaN,2,66600.0,71100.0,Rivers of Light
1100,2018-01-05,regular,6,4,0,1,2018,CHRISTMAS,0,regular,...,1,0,NaN,NaN,NaN,NaN,2,66600.0,71100.0,Rivers of Light

In [8]:
# Check if all values in 'wdw_ticket_season' are the same as 'season' in df2_2018
are_same = (df2_2018['wdw_ticket_season'] == df2_2018['season']).all()
print(f"Are all values in 'wdw_ticket_season' the same as 'season'? {are_same}")

Are all values in 'wdw_ticket_season' the same as 'season'? False